spring:
  application:
    name: redis-begin

  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
      time-to-live: 60000

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/inventory
    username: postgres
    password: Alifpass@49

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true